config/routes.rb
Tenzing::Application.routes.draw do
  resources :drink_intakes
  resources :coffee_intakes
  resources :groceries
  resources :possessions
  resources :categories
  resources :genres
  resources :books
  resources :smoke_breaks

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  match 'quick_smoke' => 'smoke_breaks#quick_smoke', :as => :quick_smoke
  match 'quick_smoke_api' => 'smokes#new', :as => :quick_smoke_api
  match 'quick_coffee' => 'coffee_intakes#quick_coffee', :as => :quick_coffee
  match 'quick_coffee_api' => 'coffee_intakes#new', :as => :quick_coffee_api
  match 'quick_drink' => 'drink_intakes#quick_drink', :as => :quick_drink
  match 'quick_drink_api' => 'drink_intakes#new', :as => :quick_drink_api


  resources :sessions

  resources :users

  get "landings/index"
  root :to => 'landings#index'
  namespace :api, :defaults => {:format => :json} do
    resources :smokes
    resources :coffees
    resources :drinks
    resources :counts
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :read, :title, :user_id, :genre_id

  belongs_to :user
  belongs_to :genre

  validates_presence_of :user
  validates_presence_of :author
  validates_presence_of :title
end
# == Schema Information
#
# Table name: books
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  author     :string(255)
#  user_id    :integer
#  read       :boolean
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  genre_id   :integer
#

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :user_id
  has_many :possessions
  
  belongs_to :user
end
# == Schema Information
#
# Table name: categories
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/coffee_intake.rb
class CoffeeIntake < ActiveRecord::Base
  attr_accessible :recorded_time, :user_id

  belongs_to :user
  validates :user, :presence => true

  def self.total_on(t)
    CoffeeIntake.all(:conditions => ["recorded_time > ? AND recorded_time < ?", t.at_beginning_of_day, t.tomorrow.at_beginning_of_day]).count
  end
end

app/models/drink_intake.rb
class DrinkIntake < ActiveRecord::Base
  attr_accessible :recorded_time, :user_id

  belongs_to :user
  validates :user, :presence => true

  def self.total_on(t)
    DrinkIntake.all(:conditions => ["recorded_time > ? AND recorded_time < ?", t.at_beginning_of_day, t.tomorrow.at_beginning_of_day]).count
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :title, :user_id

  belongs_to :user
  has_many :books

  validates_presence_of :user
  validates_presence_of :title
end
# == Schema Information
#
# Table name: genres
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/grocery.rb
class Grocery < ActiveRecord::Base
  attr_accessible :item, :location, :user_id
  
  belongs_to :user
end
# == Schema Information
#
# Table name: groceries
#
#  id         :integer         not null, primary key
#  item       :string(255)
#  location   :string(255)
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/possession.rb
class Possession < ActiveRecord::Base
  attr_accessible :category_id, :description, :title, :user_id

  belongs_to :category
  belongs_to :user
end
# == Schema Information
#
# Table name: possessions
#
#  id          :integer         not null, primary key
#  category_id :integer
#  title       :string(255)
#  user_id     :integer
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/models/smoke_break.rb
class SmokeBreak < ActiveRecord::Base
  attr_accessible :user_id, :recorded_time
  
  belongs_to :user
  validates :user, :presence => true


  def self.total_on(t)
    SmokeBreak.all(:conditions => ["recorded_time > ? AND recorded_time < ?", t.at_beginning_of_day, t.tomorrow.at_beginning_of_day]).count
  end
  
  def self.count_per_hour(t)
    SmokeBreak.all(:conditions => ["recorded_time > ? AND recorded_time < ?", t.beginning_of_hour, t.end_of_hour]).count
  end
  
  def self.date_range_per_hour
    @date = DateTime.now

    @date_array=[]
    @data_array=[]
    i = 0
    loop do 
      @date_array.push(@date.advance(:hours => -i))
      break if i==335
      i += 1
    end 
    @date_array.reverse!
  end
  
  def self.last_two_weeks_per_hour(date)
    date.each do |date|
      @data_array.push(self.count_per_hour(date))
    end
    return @data_array
  end
end
# == Schema Information
#
# Table name: smoke_breaks
#
#  id            :integer         not null, primary key
#  user_id       :integer
#  recorded_time :datetime
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation, :api_key

  attr_accessor :password
  before_save :prepare_password

  has_many :smoke_breaks
  has_many :coffee_intakes
  has_many :books
  has_many :genres
  has_many :categories
  has_many :possessions
  has_many :groceries
  has_many :drink_intakes
  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end
# == Schema Information
#
# Table name: users
#
#  id            :integer         not null, primary key
#  username      :string(255)
#  email         :string(255)
#  password_hash :string(255)
#  password_salt :string(255)
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/possessions_helper.rb
module PossessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/smoke_breaks_helper.rb
module SmokeBreaksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_footer.html.erb
<!-- Footer -->

<footer class="row">
<div class="large-12 columns">
<hr />
<div class="row">
<div class="large-6 columns">
<p>&copy; Copyright no one at all. Go to town.</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
<li><a href="#">Section 1</a></li>
<li><a href="#">Section 2</a></li>
<li><a href="#">Section 3</a></li>
<li><a href="#">Section 4</a></li>
</ul>
</div>
</div>
</div>
</footer>

app/views/shared/_nav.html.erb
<nav class="top-bar">
    <ul class="title-area">
       <li class="name">
	 <h1>
	    <a href="/">Tenzing</a>
	 </h1>
      </li>
      <li class="toggle-topbar menu-icon">
		<a href="#"><span>Menu</span></a>
      </li>
    </ul>

   <section class="top-bar-section">
      <ul class="right">
	  <li class="has-dropdown">
	    <%= link_to "Smoke Break", quick_smoke_path() %>
	    <ul class="dropdown">
			<li><%= link_to "Quick Smoke Break", quick_smoke_path() %></li>
	       <li><a href="/smoke_breaks">List Smoke Breaks</a></li>
	    </ul>

	 </li>
	 <li class="divider"></li>
	  <li class="has-dropdown">
	    <%= link_to "Coffee Break", quick_coffee_path() %>
	    <ul class="dropdown">
			<li><%= link_to "Quick Coffee Break", quick_coffee_path() %></li>
	       <li><a href="/coffee_breaks">List Coffee Breaks</a></li>
	    </ul>

	 </li>
	 <li class="divider"></li>
	  <li class="has-dropdown">
	    <%= link_to "Drink", quick_drink_path() %>
	    <ul class="dropdown">
			<li><%= link_to "Quick Drink", quick_drink_path() %></li>
	       <li><a href="/drink_intakes">List Drinks</a></li>
	    </ul>

	 </li>
	 <!-- <li class="divider"></li>
	 <li class="has-dropdown">
	    <a class="" href="/possessions">Possessions</a>
	    <ul class="dropdown">
	       <li><label>Books stuffses</a></li>
	       <li><a href="/possessions">List Possessions</a></li>
	       <li><a href="/possessions/new">Add a possessions</a></li>
	       <li class="divider"></li>
	       <li><label>Categories</label></li>
	       <li class="has-dropdown">
		   <a href="/categories">Categories</a>
		   <ul class="dropdown">
		      <li><a href="/categories/">List Categories</a></li>
		      <li><a href="/categories/new">Add Categories</a></li>
		   </ul>
	       </li>
	    </ul>
	 </li>
	 <li class="divider"></li>
	 <li class="has-dropdown">
	    <a class="" href="/books">Books</a>
	    <ul class="dropdown">
	       <li><label>Books stuffses</a></li>
	       <li><a href="/books">Library</a></li>
	       <li><a href="/books/new">Add a book</a></li>
	       <li class="divider"></li>
	       <li><label>Genre</label></li>
	       <li class="has-dropdown">
		   <a href="/genres">Genre</a>
		   <ul class="dropdown">
		      <li><a href="/genres/">List Genres</a></li>
		      <li><a href="/genres/new">Add Genre</a></li>
		   </ul>
	       </li>
	    </ul>
	 </li>
	 <li class="divider"></li>

	 <li class="has-dropdown">
	    <a class="" href="/groceries">Groceries</a>
	    <ul class="dropdown">
	       <li><label>Groceries and stuffses</a></li>
	       <li><a href="/groceries">Groceries List</a></li>
	       <li><a href="/groceries/new">Add an item</a></li>
	       <li class="divider"></li>
	    </ul>
	 </li> -->
	 <li class="divider"></li>
	 <li class="">
	    <%= link_to "Logout", logout_path() %>
	 </li>
     </ul>
   </section>
</nav>

app/views/shared/_smoke_break.html.erb
	<div class="panel">
		<!-- <h5>Consumptions per day</h5> -->
		<div id="smoke-break-chart" style="width:100%; height:400px;"></div>
	</div>

	<div class="panel">
		<!-- <h5>Consumptions per day</h5> -->
		<div id="smoke-break-chart-daily" style="width:100%; height:400px;"></div>
	</div>


<script type="text/javascript" charset="utf-8">
	$(function () {
		$('#smoke-break-chart').highcharts({
			colors: ['#0F2668', '#C15C43', '#2D4FB5', '#f7a35c', '#8085e9', '#f15c80', '#e4d354', '#2b908f', '#f45b5b', '#91e8e1'],
			chart: { 
				type: 'area'
			 },
		    title: { text: 'Consumptions' },
		    xAxis: { type: 'datetime' },
		    yAxis: {
		      title: { text: 'Smokes'}
		    },
		    series: [{
				pointInterval: <%= 1.day * 1000 %>,
				pointStart: <%= 2.weeks.ago.in_time_zone("Pacific Time (US & Canada)").at_midnight.to_i * 1000 %>,
				name: "Smokes",
				data: <%= (2.weeks.ago.in_time_zone("Pacific Time (US & Canada)").to_datetime..Time.now.in_time_zone("Pacific Time (US & Canada)").to_datetime).map { |date| current_user.smoke_breaks.total_on(date)}.inspect %>
		    },
			{
				pointInterval: <%= 1.day * 1000 %>,
				pointStart: <%= 2.weeks.ago.in_time_zone("Pacific Time (US & Canada)").at_midnight.to_i * 1000 %>,
				name: "Coffees",
				data: <%= (2.weeks.ago.in_time_zone("Pacific Time (US & Canada)").to_datetime..Time.now.in_time_zone("Pacific Time (US & Canada)").to_datetime).map { |date| current_user.coffee_intakes.total_on(date)}.inspect %>
		    },
				{
					pointInterval: <%= 1.day * 1000%>,
					pointStart: <%= 2.weeks.ago.in_time_zone("Pacific Time (US & Canada)").at_midnight.to_i * 1000 %>,
					name: "Drinks",
					data: <%= (2.weeks.ago.in_time_zone("Pacific Time (US & Canada)").to_datetime..Time.now.in_time_zone("Pacific Time (US & Canada)").to_datetime).map { |date| current_user.drink_intakes.total_on(date)}.inspect %>
			    }]
		});
		$('#smoke-break-chart-daily').highcharts({
			chart: { 
				type: 'area'
      },
		  title: { text: 'Consumptions' },
		  xAxis: { type: 'datetime' },
      yAxis: {
		    title: { text: 'Smokes'}
      },
			series: [{
				pointInterval: <%= 1.hour * 1000 %>,
				pointStart: <%= @smoke_breaks_hash[:time].to_i * 1000 %>,
				name: "Smokes",
				data: <%= @smoke_breaks_hash[:smoke_array].inspect %>
		  },
			{
				pointInterval: <%= 1.hour * 1000 %>,
				pointStart: <%= @coffee_intake_hash[:time].to_i * 1000 %>,
				name: "Coffee",
				data: <%= @coffee_intake_hash[:coffee_array].inspect %>
		  },
			{
				pointInterval: <%= 1.hour * 1000 %>,
				pointStart: <%= @drink_intake_hash[:time].to_i * 1000 %>,
				name: "Drinks",
				data: <%= @drink_intake_hash[:drink_array].inspect %>
			}]
		});
	});
</script>
	