config/routes.rb
Tenzing::Application.routes.draw do
  resources :drink_intakes
  resources :coffee_intakes
  resources :groceries
  resources :possessions
  resources :categories
  resources :genres
  resources :books
  resources :smoke_breaks

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  match 'quick_smoke' => 'smoke_breaks#quick_smoke', :as => :quick_smoke
  match 'quick_smoke_api' => 'smokes#new', :as => :quick_smoke_api
  match 'quick_coffee' => 'coffee_intakes#quick_coffee', :as => :quick_coffee
  match 'quick_coffee_api' => 'coffee_intakes#new', :as => :quick_coffee_api
  match 'quick_drink' => 'drink_intakes#quick_drink', :as => :quick_drink
  match 'quick_drink_api' => 'drink_intakes#new', :as => :quick_drink_api


  resources :sessions

  resources :users

  get "landings/index"
  root :to => 'landings#index'
  namespace :api, :defaults => {:format => :json} do
    resources :smokes
    resources :coffees
    resources :drinks
    resources :counts
  end
end

app/models/possession.rb
class Possession < ActiveRecord::Base
  attr_accessible :category_id, :description, :title, :user_id

  belongs_to :category
  belongs_to :user
end
# == Schema Information
#
# Table name: possessions
#
#  id          :integer         not null, primary key
#  category_id :integer
#  title       :string(255)
#  user_id     :integer
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/controllers/possessions_controller.rb
class PossessionsController < ApplicationController
  # GET /possessions
  # GET /possessions.json
  def index
    @possessions = current_user.possessions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @possessions }
    end
  end

  # GET /possessions/1
  # GET /possessions/1.json
  def show
    @possession = Possession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @possession }
    end
  end

  # GET /possessions/new
  # GET /possessions/new.json
  def new
    @possession = Possession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @possession }
    end
  end

  # GET /possessions/1/edit
  def edit
    @possession = Possession.find(params[:id])
  end

  # POST /possessions
  # POST /possessions.json
  def create
    @possession = current_user.possessions.new(params[:possession])
    
    respond_to do |format|
      if @possession.save
        format.html { redirect_to @possession, notice: 'Possession was successfully created.' }
        format.json { render json: @possession, status: :created, location: @possession }
      else
        format.html { render action: "new" }
        format.json { render json: @possession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /possessions/1
  # PUT /possessions/1.json
  def update
    @possession = Possession.find(params[:id])

    respond_to do |format|
      if @possession.update_attributes(params[:possession])
        format.html { redirect_to @possession, notice: 'Possession was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @possession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /possessions/1
  # DELETE /possessions/1.json
  def destroy
    @possession = Possession.find(params[:id])
    @possession.destroy

    respond_to do |format|
      format.html { redirect_to possessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/possessions_helper.rb
module PossessionsHelper
end

app/views/possessions/_form.html.erb
<div class='row'>
	
	<%= simple_form_for(@possession, html: { class: "custom "}) do |f| %>
		<fieldset>
			<legend>Possessions</legend>
			<div class='row'>
				<div class="large-10 small-8 columns">
					<div class="form-inputs">
					    <%= f.input :title, placeholder: "Title"  %>
					    <%= f.association :category, :collection => Category.all, :prompt => "Select a Category", placeholder: "Category" %>
					    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
					    <%= f.input :description, placeholder: "Description"  %>
					</div>
					<div class="row">
						<div id="display-label" class="large-1 small-1 columns">
							<%= f.button :submit %>
						</div>
					</div>
				</div>
			</div>
	<% end %>

app/views/possessions/edit.html.erb
<div class='12 columns'>
	<h1>Editing possession</h1>
	<%= render 'form' %>
	<div class='row'>
		<div class="large-11 columns">
			<%= link_to 'Show', @possession %> |
			<%= link_to 'Back', possessions_path %>
		</div>
	</div>
</div>

app/views/possessions/index.html.erb
<div class="row">
	<h1>Listing possessions</h1>
</div>

<div class="row">
	<div class="small-8 large-8 columns">
		<table>
		  <tr>
		    <th>Category</th>
		    <th>Title</th>
		    <th>User</th>
		    <th>Description</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>

		<% @possessions.each do |possession| %>
		  <tr>
		    <td><%= possession.category_id %></td>
		    <td><%= possession.title %></td>
		    <td><%= possession.user_id %></td>
		    <td><%= possession.description %></td>
		    <td><%= link_to 'Show', possession %></td>
		    <td><%= link_to 'Edit', edit_possession_path(possession) %></td>
		    <td><%= link_to 'Destroy', possession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
		</table>
	</div>
</div>
<div class='row'>
	<div class="12 columns">
		<%= link_to 'New Possession', new_possession_path, :class => "button small" %>
	</div>
</div>

app/views/possessions/new.html.erb
<div class='12 columns'>
	<h1>New possession</h1>
	<%= render 'form' %>
	<div class='row'>
		<div class="large-11 columns">
			<%= link_to 'Back', possessions_path %>
		</div>
	</div>

</div>

app/views/possessions/show.html.erb
<div class='row'>
	<div class="12 columns">
		<h2>Possession</h2>

		<p id="notice"><%= notice %></p>

		<p>
		  <b>Title:</b>
		  <%= @possession.title %>
		</p>

		<p>
		  <b>Category:</b>
			<%= link_to @possession.category.title, category_path(@possession.category) %>
		</p>

		<p>
		  <b>User:</b>
		  <%= @possession.user.username %>
		</p>

		<p>
			<b>Description:</b>
			<p><%= @possession.description %></p>
		</p>


		<%= link_to 'Edit', edit_possession_path(@possession) %> |
		<%= link_to 'Back', possessions_path %>
	</div>
</div>