config/routes.rb
Tenzing::Application.routes.draw do
  resources :drink_intakes
  resources :coffee_intakes
  resources :groceries
  resources :possessions
  resources :categories
  resources :genres
  resources :books
  resources :smoke_breaks

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  match 'quick_smoke' => 'smoke_breaks#quick_smoke', :as => :quick_smoke
  match 'quick_smoke_api' => 'smokes#new', :as => :quick_smoke_api
  match 'quick_coffee' => 'coffee_intakes#quick_coffee', :as => :quick_coffee
  match 'quick_coffee_api' => 'coffee_intakes#new', :as => :quick_coffee_api
  match 'quick_drink' => 'drink_intakes#quick_drink', :as => :quick_drink
  match 'quick_drink_api' => 'drink_intakes#new', :as => :quick_drink_api


  resources :sessions

  resources :users

  get "landings/index"
  root :to => 'landings#index'
  namespace :api, :defaults => {:format => :json} do
    resources :smokes
    resources :coffees
    resources :drinks
    resources :counts
  end
end

app/models/coffee_intake.rb
class CoffeeIntake < ActiveRecord::Base
  attr_accessible :recorded_time, :user_id

  belongs_to :user
  validates :user, :presence => true

  def self.total_on(t)
    CoffeeIntake.all(:conditions => ["recorded_time > ? AND recorded_time < ?", t.at_beginning_of_day, t.tomorrow.at_beginning_of_day]).count
  end
end

app/controllers/coffee_intakes_controller.rb
class CoffeeIntakesController < ApplicationController

  def index
    # @coffee_intakes = CoffeeIntake.all
    @coffee_intakes = current_user.coffee_intakes.all
  end

  def show
    @coffee_intake = CoffeeIntake.find(params[:id])
  end

  def new
    @coffee_intake = current_user.coffee_intakes.new
  end

  # GET /coffee_intakes/1/edit
  def edit
    @coffee_intake = CoffeeIntake.find(params[:id])
  end

  def create
    @coffee_intake = current_user.coffee_intakes.new(params[:coffee_intake])

    if @coffee_intake.save
      redirect_to @coffee_intake, notice: 'Coffee intake was successfully created.'
    else
      render action: "new" 
    end
  end

  def update
    @coffee_intake = CoffeeIntake.find(params[:id])

    if @coffee_intake.update_attributes(params[:coffee_intake])
      redirect_to @coffee_intake, notice: 'Coffee intake was successfully updated.' 
    else
      render action: "edit"
    end
  end

  def destroy
    @coffee_intake = CoffeeIntake.find(params[:id])
    @coffee_intake.destroy

    redirect_to coffee_intakes_url
  end

  def quick_coffee
    @coffee_intake = CoffeeIntake.create( :user_id => current_user.id, :recorded_time => DateTime.now )
    redirect_to root_path, :notice => "You have had #{CoffeeIntake.total_on(DateTime.now.in_time_zone("Pacific Time (US & Canada)"))} coffees times today."
  end

end

app/helpers/coffee_intakes_helper.rb
module CoffeeIntakesHelper
end

app/views/coffee_intakes/_form.html.erb
<%= simple_form_for(@coffee_intake) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :recorded_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/coffee_intakes/edit.html.erb
<h1>Editing coffee_intake</h1>

<%= render 'form' %>

<%= link_to 'Show', @coffee_intake %> |
<%= link_to 'Back', coffee_intakes_path %>

app/views/coffee_intakes/index.html.erb
<h1>Listing coffee_intakes</h1>

<table>
  <tr>
    <th>User</th>
    <th>Recorded time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coffee_intakes.each do |coffee_intake| %>
  <tr>
    <td><%= coffee_intake.user_id %></td>
    <td><%= coffee_intake.recorded_time %></td>
    <td><%= link_to 'Show', coffee_intake %></td>
    <td><%= link_to 'Edit', edit_coffee_intake_path(coffee_intake) %></td>
    <td><%= link_to 'Destroy', coffee_intake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Coffee intake', new_coffee_intake_path %>

app/views/coffee_intakes/new.html.erb
<h1>New coffee_intake</h1>

<%= render 'form' %>

<%= link_to 'Back', coffee_intakes_path %>

app/views/coffee_intakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @coffee_intake.user_id %>
</p>

<p>
  <b>Recorded time:</b>
  <%= @coffee_intake.recorded_time %>
</p>


<%= link_to 'Edit', edit_coffee_intake_path(@coffee_intake) %> |
<%= link_to 'Back', coffee_intakes_path %>