config/routes.rb
Tenzing::Application.routes.draw do
  resources :drink_intakes
  resources :coffee_intakes
  resources :groceries
  resources :possessions
  resources :categories
  resources :genres
  resources :books
  resources :smoke_breaks

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  match 'quick_smoke' => 'smoke_breaks#quick_smoke', :as => :quick_smoke
  match 'quick_smoke_api' => 'smokes#new', :as => :quick_smoke_api
  match 'quick_coffee' => 'coffee_intakes#quick_coffee', :as => :quick_coffee
  match 'quick_coffee_api' => 'coffee_intakes#new', :as => :quick_coffee_api
  match 'quick_drink' => 'drink_intakes#quick_drink', :as => :quick_drink
  match 'quick_drink_api' => 'drink_intakes#new', :as => :quick_drink_api


  resources :sessions

  resources :users

  get "landings/index"
  root :to => 'landings#index'
  namespace :api, :defaults => {:format => :json} do
    resources :smokes
    resources :coffees
    resources :drinks
    resources :counts
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :user_id
  has_many :possessions
  
  belongs_to :user
end
# == Schema Information
#
# Table name: categories
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    @possessions = @category.possessions

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
	<%= simple_form_for(@category, html: { class: "custom" }) do |f| %>
		<fieldset>
			<legend>Genre</legend>
			<div class="row">
				<div class="large-6 small-3 columns">
					<div class="form-inputs">
						<%= f.input :title, placeholder: "Category", input_html: { class: "text" } %>
					    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
					</div>
					<div class="row">
						<div id="display-label" class="large-1 small-1 columns">
							<%= f.button :submit, :class => "small" %>
						</div>
					</div>
				</div>
			</div>
	<% end %>

app/views/categories/edit.html.erb
<div class="row">
	<h1>Editing category</h1>
	<div class="12 columns">

		<%= render 'form' %>

		<div class='row display'>
			<div class="large-11 columns">
				<%= link_to 'Show', @category %> |
				<%= link_to 'Back', categories_path %>
			</div>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<div class='row'>
	<div class='12 columns'>
		<h1>Listing categories</h1>

		<table>
		  <tr>
		    <th>Title</th>
			<th>Associated Possessions</th>
		    <th>User</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>

		<% @categories.each do |category| %>
		  <tr>
		    <td><%= category.title %></td>
			<td><%= category.possessions.count %></td>
		    <td><%= category.user.username %></td>
		    <td><%= link_to 'Show', category %></td>
		    <td><%= link_to 'Edit', edit_category_path(category) %></td>
		    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
		</table>

		<br />

		<%= link_to 'New Category', new_category_path, class: "button small" %>
		
	</div>
</div>

app/views/categories/new.html.erb
<div class='row'>
	<h1>New category</h1>

	<div class='12 columns'>

	   <%= render 'form' %>
	   <div class="row display">
	      <div class="large-11 columns">
			<%= link_to 'Back', categories_path, class: "button small" %>
	      </div>
	   </div>
	</div>
</div>

app/views/categories/show.html.erb
<div class='row'>
	<div class="12 columns">
	<h2>Category</h2>
		<p id="notice"><%= notice %></p>

		<p>
		  <b>Title:</b>
		  <%= @category.title %>
		</p>

		<p>
		  <b>Associated Possessions:</b>
		  <%= @category.possessions.count %>
		</p>

		<p>
		  <b>User:</b>
		  <%= @category.user.username %>
		</p>

	<% unless @possessions.empty? %>
		<div class='12 columns'>
			<h5>Possession List:</h5>
			<table>
			  <tr>
			    <th>Title</th>
			    <th>User</th>
			    <th></th>
			    <th></th>
			    <th></th>
			  </tr>

			<% @possessions.each do |possession| %>
			  <tr>
			    <td><%= possession.title %></td>
			    <td><%= possession.user_id %></td>
			    <td><%= link_to 'Show', possession %></td>
			    <td><%= link_to 'Edit', edit_possession_path(possession) %></td>
			    <td><%= link_to 'Destroy', possession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
			</table>
		
		</div>
	<% else %>
		<p>No possessions associated with <%= @category.title %></p>
	<% end %>
		<%= link_to 'Edit', edit_category_path(@category) %> |
		<%= link_to 'Back', categories_path %>
	</div>
		</div>
</div>